import {
  Monitor,
  Server,
  Layers,
  Palette,
  Smartphone,
  Settings,
  Gamepad2,
  Star,
  Award,
  Crown,
} from "lucide-react";

// Developer titles with icons and descriptions
export const developerTitles = [
  {
    id: "frontend",
    title: "Front-End Developer",
    icon: Monitor,
    description: "UI/UX focused, client-side development",
    color: "from-blue-500 to-cyan-500",
    pattern: "frontend-pattern",
  },
  {
    id: "backend",
    title: "Back-End Developer",
    icon: Server,
    description: "Server-side logic and databases",
    color: "from-green-500 to-emerald-500",
    pattern: "backend-pattern",
  },
  {
    id: "fullstack",
    title: "Full-Stack Developer",
    icon: Layers,
    description: "End-to-end application development",
    color: "from-purple-500 to-pink-500",
    pattern: "fullstack-pattern",
  },
  {
    id: "uiux",
    title: "UI/UX Designer",
    icon: Palette,
    description: "User interface and experience design",
    color: "from-orange-500 to-red-500",
    pattern: "design-pattern",
  },
  {
    id: "mobile",
    title: "Mobile Developer",
    icon: Smartphone,
    description: "iOS and Android applications",
    color: "from-teal-500 to-blue-500",
    pattern: "mobile-pattern",
  },
  {
    id: "devops",
    title: "DevOps Engineer",
    icon: Settings,
    description: "Infrastructure and deployment",
    color: "from-yellow-500 to-orange-500",
    pattern: "devops-pattern",
  },
  {
    id: "game",
    title: "Game Developer",
    icon: Gamepad2,
    description: "Game engines and interactive media",
    color: "from-indigo-500 to-purple-500",
    pattern: "game-pattern",
  },
];

// Tech stack options based on developer title
export const techStackOptions = {
  frontend: [
    { name: "JavaScript", icon: "", category: "Language" },
    { name: "TypeScript", icon: "", category: "Language" },
    { name: "React", icon: "", category: "Framework" },
    { name: "Vue.js", icon: "", category: "Framework" },
    { name: "Angular", icon: "", category: "Framework" },
    { name: "HTML5", icon: "", category: "Markup" },
    { name: "CSS3", icon: "", category: "Styling" },
    { name: "Sass", icon: "", category: "Styling" },
  ],
  backend: [
    { name: "Python", icon: "", category: "Language" },
    { name: "Node.js", icon: "", category: "Runtime" },
    { name: "Java", icon: "", category: "Language" },
    { name: "C#", icon: "", category: "Language" },
    { name: "Go", icon: "", category: "Language" },
    { name: "PHP", icon: "", category: "Language" },
    { name: "Ruby", icon: "", category: "Language" },
    { name: "Rust", icon: "", category: "Language" },
  ],
  fullstack: [
    { name: "JavaScript", icon: "", category: "Language" },
    { name: "TypeScript", icon: "", category: "Language" },
    { name: "Python", icon: "", category: "Language" },
    { name: "React", icon: "", category: "Frontend" },
    { name: "Node.js", icon: "", category: "Backend" },
    { name: "Vue.js", icon: "", category: "Frontend" },
    { name: "Express", icon: "", category: "Backend" },
    { name: "MongoDB", icon: "", category: "Database" },
  ],
  uiux: [
    { name: "Figma", icon: "", category: "Design Tool" },
    { name: "Adobe XD", icon: "", category: "Design Tool" },
    { name: "Sketch", icon: "", category: "Design Tool" },
    { name: "Photoshop", icon: "", category: "Graphics" },
    { name: "Illustrator", icon: "", category: "Graphics" },
    { name: "Principle", icon: "", category: "Prototyping" },
  ],
  mobile: [
    { name: "Swift", icon: "", category: "iOS" },
    { name: "Kotlin", icon: "", category: "Android" },
    { name: "React Native", icon: "", category: "Cross-platform" },
    { name: "Flutter", icon: "", category: "Cross-platform" },
    { name: "Xamarin", icon: "", category: "Cross-platform" },
    { name: "Ionic", icon: "", category: "Hybrid" },
  ],
  devops: [
    { name: "Docker", icon: "", category: "Container" },
    { name: "Kubernetes", icon: "", category: "Orchestration" },
    { name: "AWS", icon: "", category: "Cloud" },
    { name: "Azure", icon: "", category: "Cloud" },
    { name: "Jenkins", icon: "", category: "CI/CD" },
    { name: "Terraform", icon: "", category: "Infrastructure" },
  ],
  game: [
    { name: "Unity", icon: "", category: "Engine" },
    { name: "Unreal Engine", icon: "", category: "Engine" },
    { name: "C++", icon: "", category: "Language" },
    { name: "C#", icon: "", category: "Language" },
    { name: "Godot", icon: "", category: "Engine" },
    { name: "Blender", icon: "", category: "3D Modeling" },
  ],
} as const;

// Experience levels
export const experienceLevels = [
  {
    id: "junior",
    title: "Junior Developer",
    subtitle: "0-2 years experience",
    icon: Star,
    color: "from-green-400 to-blue-400",
    description: "Starting your coding journey",
  },
  {
    id: "mid",
    title: "Mid-Level Developer",
    subtitle: "2-5 years experience",
    icon: Award,
    color: "from-blue-400 to-purple-400",
    description: "Building solid expertise",
  },
  {
    id: "senior",
    title: "Senior Developer",
    subtitle: "5+ years experience",
    icon: Crown,
    color: "from-purple-400 to-pink-400",
    description: "Leading and mentoring others",
  },
];
